[build]
  builder = "DOCKERFILE"

[deploy]
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300

[env]
  PORT = "3001"
  NODE_ENV = "production"
  PYTHONPATH = "/app"
